import type { Member, Preference, Activity, ActivitySignup, Feedback, QuizQuestion, ActivityInvitation } from '@/types';

export const mockMembers: Member[] = [
  {
    id: 'm1',
    name: '林推理',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=detective',
    role: 'president',
    level: 'core',
    joinDate: '2024-09-01',
    activityCount: 23,
  },
  {
    id: 'm2',
    name: '苏脑洞',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=creative',
    role: 'member',
    level: 'experienced',
    joinDate: '2024-10-15',
    activityCount: 12,
  },
  {
    id: 'm3',
    name: '王小新',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=newbie',
    role: 'member',
    level: 'new',
    joinDate: '2025-03-10',
    activityCount: 2,
  },
  {
    id: 'm4',
    name: '陈逻辑',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=logic',
    role: 'member',
    level: 'core',
    joinDate: '2024-09-15',
    activityCount: 18,
  },
  {
    id: 'm5',
    name: '周欢乐',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=happy',
    role: 'member',
    level: 'experienced',
    joinDate: '2024-11-20',
    activityCount: 9,
  },
  {
    id: 'm6',
    name: '吴萌新',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fresh',
    role: 'member',
    level: 'new',
    joinDate: '2025-04-01',
    activityCount: 0,
  },
  {
    id: 'm7',
    name: '郑演员',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=actor',
    role: 'member',
    level: 'experienced',
    joinDate: '2024-10-01',
    activityCount: 15,
  },
  {
    id: 'm8',
    name: '孙酱油',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chill',
    role: 'member',
    level: 'new',
    joinDate: '2025-02-15',
    activityCount: 3,
  },
];

export const mockPreferences: Record<string, Preference> = {
  m1: {
    memberId: 'm1',
    scores: {
      logicReasoning: 5,
      worldBuilding: 3,
      npcAcceptance: 4,
      edgeRoleTolerance: 4,
      socialPreference: 3,
    },
    tags: ['本格达人', '逻辑怪', '推土机', '不挑角色'],
    lastUpdated: '2025-05-10',
    hasCompletedQuiz: true,
    history: [
      { date: '2024-09', scores: { logicReasoning: 4, worldBuilding: 2, npcAcceptance: 3, edgeRoleTolerance: 3, socialPreference: 3 } },
      { date: '2024-12', scores: { logicReasoning: 4.5, worldBuilding: 2.5, npcAcceptance: 3.5, edgeRoleTolerance: 3.5, socialPreference: 3 } },
      { date: '2025-03', scores: { logicReasoning: 5, worldBuilding: 3, npcAcceptance: 4, edgeRoleTolerance: 4, socialPreference: 3 } },
    ],
  },
  m2: {
    memberId: 'm2',
    scores: {
      logicReasoning: 3,
      worldBuilding: 5,
      npcAcceptance: 5,
      edgeRoleTolerance: 3,
      socialPreference: 4,
    },
    tags: ['变格爱好者', '脑洞王者', '戏精附体', '沉浸体验派'],
    lastUpdated: '2025-05-08',
    hasCompletedQuiz: true,
    history: [
      { date: '2024-10', scores: { logicReasoning: 2, worldBuilding: 4, npcAcceptance: 4, edgeRoleTolerance: 2, socialPreference: 3 } },
      { date: '2025-01', scores: { logicReasoning: 2.5, worldBuilding: 5, npcAcceptance: 5, edgeRoleTolerance: 2.5, socialPreference: 3.5 } },
      { date: '2025-04', scores: { logicReasoning: 3, worldBuilding: 5, npcAcceptance: 5, edgeRoleTolerance: 3, socialPreference: 4 } },
    ],
  },
  m3: {
    memberId: 'm3',
    scores: {
      logicReasoning: 3,
      worldBuilding: 3,
      npcAcceptance: 2,
      edgeRoleTolerance: 2,
      socialPreference: 4,
    },
    tags: ['萌新玩家', '社交达人', '需要引导'],
    lastUpdated: '2025-04-15',
    hasCompletedQuiz: true,
    history: [
      { date: '2025-03', scores: { logicReasoning: 3, worldBuilding: 3, npcAcceptance: 2, edgeRoleTolerance: 2, socialPreference: 4 } },
    ],
  },
  m4: {
    memberId: 'm4',
    scores: {
      logicReasoning: 5,
      worldBuilding: 4,
      npcAcceptance: 3,
      edgeRoleTolerance: 5,
      socialPreference: 2,
    },
    tags: ['硬核推土机', '细节控', '边缘角色专业户', '安静盘本'],
    lastUpdated: '2025-05-12',
    hasCompletedQuiz: true,
    history: [
      { date: '2024-09', scores: { logicReasoning: 4, worldBuilding: 3, npcAcceptance: 2, edgeRoleTolerance: 4, socialPreference: 2 } },
      { date: '2025-01', scores: { logicReasoning: 5, worldBuilding: 3.5, npcAcceptance: 2.5, edgeRoleTolerance: 5, socialPreference: 2 } },
      { date: '2025-04', scores: { logicReasoning: 5, worldBuilding: 4, npcAcceptance: 3, edgeRoleTolerance: 5, socialPreference: 2 } },
    ],
  },
  m5: {
    memberId: 'm5',
    scores: {
      logicReasoning: 2,
      worldBuilding: 3,
      npcAcceptance: 4,
      edgeRoleTolerance: 4,
      socialPreference: 5,
    },
    tags: ['欢乐喜剧人', '气氛担当', '机制小能手', '交友狂魔'],
    lastUpdated: '2025-05-05',
    hasCompletedQuiz: true,
    history: [
      { date: '2024-11', scores: { logicReasoning: 2, worldBuilding: 2, npcAcceptance: 3, edgeRoleTolerance: 3, socialPreference: 4 } },
      { date: '2025-02', scores: { logicReasoning: 2, worldBuilding: 3, npcAcceptance: 4, edgeRoleTolerance: 4, socialPreference: 5 } },
    ],
  },
  m6: {
    memberId: 'm6',
    scores: {
      logicReasoning: 3,
      worldBuilding: 3,
      npcAcceptance: 3,
      edgeRoleTolerance: 3,
      socialPreference: 3,
    },
    tags: ['未测评'],
    lastUpdated: '2025-04-01',
    hasCompletedQuiz: false,
    history: [],
  },
  m7: {
    memberId: 'm7',
    scores: {
      logicReasoning: 3,
      worldBuilding: 5,
      npcAcceptance: 5,
      edgeRoleTolerance: 3,
      socialPreference: 4,
    },
    tags: ['NPC 杀手', '情感喷泉', '变格狂人', '演技派'],
    lastUpdated: '2025-05-11',
    hasCompletedQuiz: true,
    history: [
      { date: '2024-10', scores: { logicReasoning: 2, worldBuilding: 4, npcAcceptance: 4, edgeRoleTolerance: 2, socialPreference: 3 } },
      { date: '2025-01', scores: { logicReasoning: 2.5, worldBuilding: 5, npcAcceptance: 5, edgeRoleTolerance: 2.5, socialPreference: 3.5 } },
      { date: '2025-04', scores: { logicReasoning: 3, worldBuilding: 5, npcAcceptance: 5, edgeRoleTolerance: 3, socialPreference: 4 } },
    ],
  },
  m8: {
    memberId: 'm8',
    scores: {
      logicReasoning: 2,
      worldBuilding: 3,
      npcAcceptance: 3,
      edgeRoleTolerance: 5,
      socialPreference: 4,
    },
    tags: ['佛系玩家', '边缘位不慌', '打本交友', '随遇而安'],
    lastUpdated: '2025-04-20',
    hasCompletedQuiz: true,
    history: [
      { date: '2025-02', scores: { logicReasoning: 2, worldBuilding: 3, npcAcceptance: 3, edgeRoleTolerance: 4, socialPreference: 4 } },
    ],
  },
};

export const mockActivities: Activity[] = [
  {
    id: 'a1',
    title: '周六下午推理局',
    scriptName: '《时光杀机》',
    type: 'honkaku',
    date: '2025-06-21',
    time: '14:00',
    totalSlots: 6,
    veteranRatio: 0.5,
    status: 'upcoming',
    description: '经典本格推理本，三重密室，逻辑严密。适合喜欢盘逻辑的玩家。',
    createdBy: 'm1',
    createdAt: '2025-06-15',
  },
  {
    id: 'a2',
    title: '周日变格沉浸场',
    scriptName: '《梦中的幽灵》',
    type: 'henkaku',
    date: '2025-06-22',
    time: '19:00',
    totalSlots: 7,
    veteranRatio: 0.4,
    status: 'upcoming',
    description: '超现实变格本，世界观宏大，NPC 互动多，需要脑洞大开。',
    createdBy: 'm1',
    createdAt: '2025-06-16',
  },
  {
    id: 'a3',
    title: '周五欢乐机制夜',
    scriptName: '《首富争夺战》',
    type: 'fun',
    date: '2025-06-20',
    time: '18:30',
    totalSlots: 8,
    veteranRatio: 0.3,
    status: 'upcoming',
    description: '欢乐机制阵营本，游戏性强，适合放松社交，新手友好。',
    createdBy: 'm1',
    createdAt: '2025-06-14',
  },
  {
    id: 'a4',
    title: '周三混合体验场',
    scriptName: '《雾都往事》',
    type: 'mixed',
    date: '2025-06-18',
    time: '19:00',
    totalSlots: 6,
    veteranRatio: 0.5,
    status: 'ended',
    description: '本格推理与变格设定结合的混合本，既有逻辑又有故事。',
    createdBy: 'm1',
    createdAt: '2025-06-10',
  },
  {
    id: 'a5',
    title: '上周六推理局',
    scriptName: '《图书馆疑云》',
    type: 'honkaku',
    date: '2025-06-14',
    time: '14:00',
    totalSlots: 6,
    veteranRatio: 0.5,
    status: 'ended',
    description: '校园题材本格推理，经典暴风雪山庄模式。',
    createdBy: 'm1',
    createdAt: '2025-06-08',
  },
];

export const mockSignups: ActivitySignup[] = [
  { id: 's1', activityId: 'a1', memberId: 'm1', matchScore: 92, tier: 'core', signedUpAt: '2025-06-15 10:00' },
  { id: 's2', activityId: 'a1', memberId: 'm4', matchScore: 95, tier: 'core', signedUpAt: '2025-06-15 10:05' },
  { id: 's3', activityId: 'a1', memberId: 'm2', matchScore: 65, tier: 'experience', signedUpAt: '2025-06-15 11:00' },
  { id: 's4', activityId: 'a1', memberId: 'm3', matchScore: 55, tier: 'experience', signedUpAt: '2025-06-15 12:00' },
  { id: 's5', activityId: 'a1', memberId: 'm8', matchScore: 48, tier: 'substitute', signedUpAt: '2025-06-15 14:00' },
  { id: 's6', activityId: 'a2', memberId: 'm2', matchScore: 94, tier: 'core', signedUpAt: '2025-06-16 09:00' },
  { id: 's7', activityId: 'a2', memberId: 'm7', matchScore: 96, tier: 'core', signedUpAt: '2025-06-16 09:10' },
  { id: 's8', activityId: 'a2', memberId: 'm5', matchScore: 72, tier: 'experience', signedUpAt: '2025-06-16 10:00' },
  { id: 's9', activityId: 'a2', memberId: 'm1', matchScore: 60, tier: 'experience', signedUpAt: '2025-06-16 10:30' },
  { id: 's10', activityId: 'a3', memberId: 'm5', matchScore: 95, tier: 'core', signedUpAt: '2025-06-14 20:00' },
  { id: 's11', activityId: 'a3', memberId: 'm8', matchScore: 78, tier: 'experience', signedUpAt: '2025-06-14 20:30' },
  { id: 's12', activityId: 'a3', memberId: 'm3', matchScore: 70, tier: 'experience', signedUpAt: '2025-06-14 21:00' },
  { id: 's13', activityId: 'a3', memberId: 'm6', matchScore: 50, tier: 'substitute', signedUpAt: '2025-06-15 08:00' },
];

export const mockFeedbacks: Feedback[] = [
  {
    id: 'f1',
    activityId: 'a4',
    memberId: 'm1',
    scriptRating: 4,
    atmosphereRating: 5,
    comment: '混合本的设定很有意思，逻辑和脑洞结合得不错，氛围超棒！',
    submittedAt: '2025-06-19 10:00',
  },
  {
    id: 'f2',
    activityId: 'a4',
    memberId: 'm2',
    scriptRating: 5,
    atmosphereRating: 4,
    comment: '变格部分我很喜欢，推理部分也有得盘，整体体验很好。',
    submittedAt: '2025-06-19 11:00',
  },
  {
    id: 'f3',
    activityId: 'a4',
    memberId: 'm3',
    scriptRating: 3,
    atmosphereRating: 4,
    comment: '第一次玩混合本，有点懵但是大家都很照顾我，氛围不错。',
    submittedAt: '2025-06-19 12:00',
  },
  {
    id: 'f4',
    activityId: 'a5',
    memberId: 'm1',
    scriptRating: 5,
    atmosphereRating: 4,
    comment: '经典本格，推理链条很完整，盘得很爽！',
    submittedAt: '2025-06-15 18:00',
  },
  {
    id: 'f5',
    activityId: 'a5',
    memberId: 'm4',
    scriptRating: 4,
    atmosphereRating: 3,
    comment: '手法设计不错，就是人有点少氛围一般。',
    submittedAt: '2025-06-15 19:00',
  },
];

export const quizQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    question: '你更喜欢哪种打本体验？',
    options: [
      { label: '逐条盘线索，享受逻辑链闭环的快感', value: 5, dimension: 'logicReasoning' },
      { label: '大开脑洞，探索奇奇怪怪的世界观', value: 5, dimension: 'worldBuilding' },
      { label: '和大家嘻嘻哈哈，开心最重要', value: 5, dimension: 'socialPreference' },
      { label: '沉浸角色，体验不同人生', value: 3, dimension: 'npcAcceptance' },
    ],
  },
  {
    id: 'q2',
    question: '遇到 NPC 演绎环节，你会？',
    options: [
      { label: '超期待！我就是戏精本精', value: 5, dimension: 'npcAcceptance' },
      { label: '可以接受，别太尬就行', value: 3, dimension: 'npcAcceptance' },
      { label: '有点社恐，希望少点互动', value: 1, dimension: 'npcAcceptance' },
      { label: '完全看 NPC 演技', value: 3, dimension: 'npcAcceptance' },
    ],
  },
  {
    id: 'q3',
    question: '如果分到了边缘角色，你会？',
    options: [
      { label: '完全不介意，我可以自己找乐子', value: 5, dimension: 'edgeRoleTolerance' },
      { label: '有点小失落，但也能玩下去', value: 3, dimension: 'edgeRoleTolerance' },
      { label: '会很不爽，影响体验', value: 1, dimension: 'edgeRoleTolerance' },
      { label: '我运气不会那么差吧', value: 3, dimension: 'edgeRoleTolerance' },
    ],
  },
  {
    id: 'q4',
    question: '你打本更看重什么？',
    options: [
      { label: '诡计精妙，逻辑自洽', value: 5, dimension: 'logicReasoning' },
      { label: '设定新奇，世界观宏大', value: 5, dimension: 'worldBuilding' },
      { label: '认识新朋友，社交属性', value: 5, dimension: 'socialPreference' },
      { label: '情感共鸣，催泪治愈', value: 3, dimension: 'npcAcceptance' },
    ],
  },
  {
    id: 'q5',
    question: '一个本格推理本和一个变格沉浸本同时开，你选？',
    options: [
      { label: '必须本格！我是推土机', value: 5, dimension: 'logicReasoning' },
      { label: '选变格！我要开脑洞', value: 5, dimension: 'worldBuilding' },
      { label: '看哪个朋友多', value: 5, dimension: 'socialPreference' },
      { label: '好纠结，都行', value: 3, dimension: 'logicReasoning' },
    ],
  },
];

export const CURRENT_USER_ID = 'm3';

export const mockInvitations: ActivityInvitation[] = [
  {
    id: 'inv1',
    activityId: 'a1',
    memberId: 'm5',
    invitedBy: 'm1',
    status: 'pending',
    message: '周六推理局缺个老玩家撑场子，来吗？',
    createdAt: '2025-06-19 14:30',
  },
  {
    id: 'inv2',
    activityId: 'a2',
    memberId: 'm4',
    invitedBy: 'm1',
    status: 'declined',
    message: '周日变格本需要个逻辑强的，来补个位呗',
    createdAt: '2025-06-18 10:00',
    respondedAt: '2025-06-18 12:00',
  },
];

